name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - h5py
  - numpy
  - matplotlib
  - gdal
  - pip:
      - awscli
      - git+https://github.com/tylere/pykml.git
